### ISSUE TITLE
In deno, the filename should not be named like "index.ts"

### ISSUE THREAD

**Issue by p1atdev** [railwayapp/templates#281]
According [official manual](https://deno.land/manual/contributing/style_guide#do-not-use-the-filename-indextsindexjs), we should not use filename `index.ts/index.js`.
I think we should use the name like `server.ts` instead.

**Comment by FarazPatankar** [comment]
Closing this as we've restructured how we manage templates. Feel free to open a PR with the suggested change on the [new repo](https://github.com/railwayapp-templates/deno).
