### ISSUE TITLE
Add PocketBase Template

### ISSUE THREAD

**Issue by abdfnx** [railwayapp/templates#371]
### Template URL

https://railway.app/new/template/WgwpLG

### What does this template deploy?

This template deploys [PocketBase](https://pocketbase.io), an Open Source realtime backend in 1 file

### Demo project

https://railway.app/project/6bf14943-b1bb-4a87-b0b8-a631a1ff6be8

**Comment by FarazPatankar** [comment]
Doesn't PocketBase use SQLite? Does this mean the data will be lost on every re-deploy?

**Comment by abdfnx** [comment]
> Doesn't PocketBase use SQLite? Does this mean the data will be lost on every re-deploy?

I don't think so
