### ISSUE TITLE
⚡️ Bun + Bao.js Railway Template Submission

### ISSUE THREAD

**Issue by mattreid1** [railwayapp/templates#373]
### Template URL

https://railway.app/new/template/gxxk5g

### What does this template deploy?

This is a template for the [Bao.js](https://github.com/mattreid1/baojs) webserver running on the [Bun](https://bun.sh/) JavaScript runtime.

It is a simple example, responding with a short hello world message. You can find a live deployed version of it [here](https://baojs-production.up.railway.app/).

### Demo project

https://railway.app/project/1133b967-d96a-49ce-8ebd-eb39b122be42/service/6f32e4c3-2619-4cb5-a404-2de828ee4231

**Comment by FarazPatankar** [comment]
This is awesome, thanks for the contribution!
