### ISSUE TITLE
Add Waline template

### ISSUE THREAD

**Issue by lizheming** [railwayapp/templates#374]
### Template URL

https://railway.app/new/template/UZB84v?referralCode=lizheming

### What does this template deploy?

[Waline](https://github.com/walinejs/waline): A simple, safe comment system.

**Comment by FarazPatankar** [comment]
Hey @lizheming, thanks for the PR. Do you mind adding the Waline logo to [devicons](https://github.com/railwayapp/devicons) and then I can merge your PR?

**Comment by lizheming** [comment]
@FarazPatankar OK, https://github.com/railwayapp/devicons/pull/47 I have crated a pull request to add waline logo.

**Comment by FarazPatankar** [comment]
Approved. It should show up on our templates page soon! 😄
