### ISSUE TITLE
Add Livebook Template to Railway

### ISSUE THREAD

**Issue by joeybellerose** [railwayapp/templates#378]
### Template URL

https://railway.app/new/template/vg_Efh?referralCode=zdYM_p

### What does this template deploy?

This template will deploy the latest version of [Livebook](https://livebook.dev).

Livebook is an interactive analytical notebook for the [elixir](https://elixir-lang.org) programming language.

It enables users to quickly iterate through their Data Science workflows to include:

* Data Visualization
* Data Transformation
* Machine Learning Models
* Team Collaboration

**Comment by FarazPatankar** [comment]
Approved! 😄
