### ISSUE TITLE
Update Metabase template

### ISSUE THREAD

**Issue by alphasecio** [railwayapp/templates#379]
### Template URL

https://railway.app/new/template/6gpAuM?referralCode=alphasec

### What does this template deploy?

This template deploys the open-source business intelligence platform, Metabase.

I created a new one as the existing template for Metabase does not work.

I've also published an accompanying blog post to help Railway users: https://alphasec.io/open-source-business-intelligence-with-metabase/

**Comment by FarazPatankar** [comment]
The current one seems to work fine? What issues did you face with it?

**Comment by alphasecio** [comment]
It's weird, but you are right, I'm able to deploy using the default template now. Feel free to ignore my template, but would appreciate if you can add the accompanying post though.

**Comment by FarazPatankar** [comment]
Could you update your post to point to the template listed on the website and then I can link back to your post?

Also, would be interested in writing some posts directly on our blog? Happy to discuss this over Discord/Twitter/Email whichever is easiest for you!

**Comment by alphasecio** [comment]
Done - I've updated the links back to the original template.
