### ISSUE TITLE
Add Caddy template

### ISSUE THREAD

**Issue by alphasecio** [railwayapp/templates#380]
### Template URL

https://railway.app/new/template/TETV8z?referralCode=alphasec

### What does this template deploy?

This template deploys a static website on Railway using the popular Caddy server.

I've also published an accompanying blog post to help Railway users: https://alphasec.io/how-to-deploy-a-static-website-with-caddy-on-railway/

**Comment by FarazPatankar** [comment]
Thanks for the submission, I have approved this template! 😄
