### ISSUE TITLE
Apollo "Hack the Supergraph" Template

### ISSUE THREAD

**Issue by dbanty** [railwayapp/templates#384]
### Template URL

https://railway.app/new/template/fyuqlV

### What does this template deploy?

This template is a way to experiment with an Apollo supergraph (multiple GraphQL services combined via [Apollo Federation](https://www.apollographql.com/docs/federation/)). We use this as an educational tool to help people learn about federation & GraphOS over in https://github.com/apollographql/hack-the-supergraph .

### Demo project

https://railway.app/project/8e9b9ba3-aa16-4715-92de-8a35529f678c

**Comment by FarazPatankar** [comment]
Hey hey, sorry for the lack of responsiveness here. The template publishing for is now entirely self-serve via our dashboard. You should simply be able to visit your [account templates page](https://railway.app/account/templates) and publish your template by filling out the publishing form.

You can also read more in our [docs](https://docs.railway.app/reference/templates#publishing-a-template)!
