### ISSUE TITLE
Railway Template Submission

### ISSUE THREAD

**Issue by DevMaxC** [railwayapp/templates#389]
### Template URL

https://railway.app/new/template/pXu4Vv?referralCode=qL1H20

### What does this template deploy?

I was having a load of trouble deploying selenium and fast api to railway so I made the template. Before i had certain issues which the docker file fixes :)

Judging from looking at the discord there are lots of others too who struggle with selenium.

**Comment by FarazPatankar** [comment]
Hey hey, sorry for the lack of responsiveness here. The template publishing for is now entirely self-serve via our dashboard. You should simply be able to visit your [account templates page](https://railway.app/account/templates) and publish your template by filling out the publishing form.

You can also read more in our [docs](https://docs.railway.app/reference/templates#publishing-a-template)!
