### ISSUE TITLE
Railway Template Submission - Sapphire Discord bot

### ISSUE THREAD

**Issue by FantomeBeignet** [railwayapp/templates#395]
### Template URL

https://railway.app/new/template/4v1jeR

### What does this template deploy?

This project deploys a simple Discord bot using TypeScript and the [Sapphire](https://www.sapphirejs.dev/) library.

**Comment by FarazPatankar** [comment]
Hey hey, sorry for the lack of responsiveness here. The template publishing for is now entirely self-serve via our dashboard. You should simply be able to visit your [account templates page](https://railway.app/account/templates) and publish your template by filling out the publishing form.

You can also read more in our [docs](https://docs.railway.app/reference/templates#publishing-a-template)!
