### ISSUE TITLE
Railway Template Submission - Descope Authentication app

### ISSUE THREAD

**Issue by meirwah** [railwayapp/templates#398]
### Template URL

https://railway.app/template/hwqiFX?referralCode=dsf6rb

### What does this template deploy?

I created this template to demonstrate how can you embedded Descope login/signup component in a Vite+React  app.

Descope provides a free Tier for Authentication for any app https://www.descope.com/ 

This example includes Passkeys and Enchanted links as auth methods, but Descope supports many more (SSO/SAML/OTP/Magic Link/TOTP)

Important disclaimer:  this app includes only the frontend embedding, for session validation to your backend routes , plz read https://docs.descope.com/build/guides/session/

**Comment by FarazPatankar** [comment]
Hey hey, sorry for the lack of responsiveness here. The template publishing for is now entirely self-serve via our dashboard. You should simply be able to visit your [account templates page](https://railway.app/account/templates) and publish your template by filling out the publishing form.

You can also read more in our [docs](https://docs.railway.app/reference/templates#publishing-a-template)!
