### ISSUE TITLE
Update Express Starter

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#411]
## Goal
A minimalistic Express.js starter template to kickstart Node.js web server projects.

## Payout
$50

## Expectation
Create an Express.js template with a basic server setup and routes. Include package.json configuration and a simple "Hello World" endpoint. Bonus points for middleware examples and concise documentation.

**Comment by animeshdas2000** [comment]
Hey @ndneighbor, I'd like to attempt this bounty. Can you assign this to me?

**Comment by Shivam-Batham** [comment]
@ndneighbor  can i work on this ??

**Comment by ndneighbor** [comment]
Indeed you can! Lemme know if you have any issues along the way.

**Comment by melissa-hale** [comment]
completed by @vimode

template repo: https://github.com/railwayapp-templates/node-express
template page: https://railway.app/template/Vp8hse
