### ISSUE TITLE
Add Go Mux Starter

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#414]
# Goal
An efficient Go Mux starter template to kickstart your Go web application development using the powerful Mux router.

## Payout
$50

## Expectation
Contribute a well-structured Go Mux starter template that showcases the usage of the Mux router. Include basic server setup, routing examples, and middleware implementation.

**Comment by himeshp** [comment]
Here - https://github.com/railwayapp/templates/issues/448

**Comment by melissa-hale** [comment]
completed by @brody129

template repo: https://github.com/railwayapp-templates/go-mux
template page: https://railway.app/template/_eGomU

closing as completed, but payout is pending
