### ISSUE TITLE
Add Rust Starter

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#415]
# Goal
A robust Rust starter template for building high-performance web applications.

## Payout
$50

## Expectation
Create a Rust template with a simple web server and routing. Showcase Rust's strong points and error handling. Comprehensive documentation is crucial. Empower developers to dive into Rust web development!

**Comment by Milo123459** [comment]
this is mine

**Comment by melissa-hale** [comment]
completed by @Milo123459 !

template repo: https://github.com/railwayapp-templates/rust-starter
