### ISSUE TITLE
Add NSQ Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#421]
# Goal
A streamlined NSQ template to set up a lightweight and fast message queue system.

## Payout
$250

## Expectation
Contribute an NSQ template showcasing topic creation, message publishing, and subscription mechanisms. Ensure the template is scalable and easy to manage. Detailed documentation will guide users in harnessing the power of NSQ for their projects.

**Comment by ndneighbor** [comment]
# Goal
A streamlined NSQ template to set up a lightweight and fast message queue system.

## Payout
$250

## Expectation
Contribute an NSQ template showcasing topic creation, message publishing, and subscription mechanisms. Ensure the template is scalable and easy to manage. Detailed documentation will guide users in harnessing the power of NSQ for their projects.

**Comment by Aravindha1234u** [comment]
Will work on this

**Comment by Aravindha1234u** [comment]
Template: https://railway.app/template/okc9Wi?referralCode=HT4TtK
Github Repo: https://github.com/Aravindha1234u/nsq-railway

@ndneighbor

**Comment by melissa-hale** [comment]
Nice work @Aravindha1234u, deploying from the template spun up the cluster nicely and everything looks to be ready to roll.  Some feedback though - as a user who is interested in consuming this template, I am not given information to guide me in actually using it in a stack -
1. how do I create a topic?
2. how do I publish a message to the topic?
3. how do I subscribe to a topic?
4. can I manage my topics from a file in the template repo?

It would be nice to see a working demo, but addressing these in the Documentation would be great too.

**Comment by melissa-hale** [comment]
same goes for this one.  once you've addressed the above, please push your code here: https://github.com/railwayapp-templates/nsq and update the template config to point here.

then just give me an ack, i'll make a final pass, and we're clear for payout

**Comment by Aravindha1234u** [comment]
Hi @melissa-hale, I have updated the documentation with examples and usage. Also, I have pushed the field to the new repo and modified the railway template to point there.
