### ISSUE TITLE
Add RabbitMQ Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#425]
# Goal
A feature-rich RabbitMQ template for building robust and scalable message queue systems.

## Payout
$250

## Expectation
Contribute a RabbitMQ template showcasing queue creation, message publishing, and consumer handling. Consider demonstrating RabbitMQ clustering and high-availability configurations. Comprehensive documentation will assist users in making the most of RabbitMQ.

**Comment by melissa-hale** [comment]
completed by @6ixfalls

template repo: https://github.com/railwayapp-templates/rabbitmq
