### ISSUE TITLE
Add Imgproxy Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#430]
# Goal
Imgproxy is a self-hosted template for image hosting and on-the-fly image processing.

## Payout
$150

## Expectation
Develop the Imgproxy template with seamless integration for image hosting and manipulation. It should allow users to resize, crop, and optimize images on-the-fly. Provide clear documentation on how to set up and configure Imgproxy to enable users to manage their images effectively.

**Comment by Aravindha1234u** [comment]
Github Repo: 
https://github.com/Aravindha1234u/imgproxy-railway

Template: https://railway.app/template/x4G-nB?referralCode=HT4TtK

**Comment by melissa-hale** [comment]
> Github Repo: https://github.com/Aravindha1234u/imgproxy-railway
> 
> Template: https://railway.app/template/x4G-nB?referralCode=HT4TtK

Hi @Aravindha1234u !  Thank you for your submission on this template bounty, but we have gone with a submission that slid in just before yours

**Comment by melissa-hale** [comment]
completed by @ItzDerock

template https://railway.app/template/d7gCBH
