### ISSUE TITLE
Add NocoDB Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#432]
# Goal
NocoDB is an automation for DBs to become low code applications for creating self-hosted database applications with ease.

## Payout
$200

## Expectation
Develop the NocoDB template, allowing users to quickly set up self-hosted database applications.

**Comment by 6ixfalls** [comment]
I've published a NocoDB template on Railway here (aff link):
https://railway.app/template/opu-NU?referralCode=IQhE0B
Not sure where to submit this, but I'm assuming putting this here would be sufficient. Thanks!

**Comment by melissa-hale** [comment]
completed by @6ixfalls!

template repo: https://github.com/railwayapp-templates/nocodb
