### ISSUE TITLE
Add Shynet Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#436]
# Goal
Shynet is an analytics template for self-hosted website analytics and data visualization.

## Payout
$150

## Expectation
Contribute the Shynet template with an easy setup process for website tracking and data visualization. It should provide basic analytics, including unique visitors, popular pages, and referrers. Ensure that the template is lightweight and user-friendly. Clear documentation will assist users in effectively using Shynet for their analytics needs.

**Comment by MatteoGauthier** [comment]
Hey Railway team ! Is it possible to take this task ?

Have a nice day ☀️

**Comment by MatteoGauthier** [comment]
## Progression

- [x] Setup deployments
- [x] Admin user creation script
- [x] Testing
- [ ] Documentation of the template
- [ ] Publishing of the template

Here is the repository with the template code : <https://github.com/MatteoGauthier/shynet-railway>

**Comment by MatteoGauthier** [comment]
The template is now published with instructions ! Here is the [template link](https://railway.app/template/yW3Kos?referralCode=Matteo) ✅

[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/template/yW3Kos?referralCode=Matteo)

**Comment by ndneighbor** [comment]
Beautiful, will be reviewing this tomorrow my time.

**Comment by melissa-hale** [comment]
Amazing work @MatteoGauthier , thank you for the submission.  I especially love how you included a railway.toml file, and your Overview/Readme is so good ✨

I'm happy to accept your submission and get the payout process going.  I have created a repository for you here: https://github.com/railwayapp-templates/shynet.  Please push your code to this repo and update the template configuration to point to this one.  Once done, please send me an email at melissa@railway.app and we'll finish it out.

Thanks again!

**Comment by MatteoGauthier** [comment]
@melissa-hale I've just emailed you! Have a nice day, and thanks again for this opportunity
