### ISSUE TITLE
Imgproxy

### ISSUE THREAD

**Issue by ItzDerock** [railwayapp/templates#443]
### Contact Details

derock@derock.dev (or derock on discord)

### Template URL

https://railway.app/template/d7gCBH

### What does this template deploy?

#430 - Imgproxy

Deploys 1 instance of imgproxy from the [darthsim/imgproxy](https://hub.docker.com/r/darthsim/imgproxy/) docker image. 

Sets up health checks and sets some common/useful environment variables to what I believe are sensible defaults.

I tried using `{{ secret(32, "abcdefghijklmnopqrstuvwxyz=/+") }}` to auto-generate the key and salt, but the result is not a valid base64 string and imgproxy wouldn't boot. 

## Examples
These will stay up for as long as needed. imgproxy is very lightweight so I don't care too much about costs. These demos are using a live instance of imgproxy from this template running on Railway.

### Original Image (JPG)
![image](https://derock.media/70ZZGG.jpg)

## Downscaled to 1080p and converted to webp
![downscaled, 1080p, webp](https://imgproxy-production-fcac.up.railway.app/WsM0QiK6xauNx0r7D7eU6ynCwL2WTEFOgnxhJOSBAxQ/rs:fit:1080:1920:0/g:no/aHR0cHM6Ly9kZXJvY2subWVkaWEvNzBaWkdHLmpwZw.webp)

## Cropped to phone wallpaper (2500x1000 webp)
![1000x2500](https://imgproxy-production-fcac.up.railway.app/3Upp_mVvVhzC31sGA_MIYeLxn0PnRvsxKIsIc9L9w9k/rs:fill:1000:2500:0/g:no/aHR0cHM6Ly9kZXJvY2subWVkaWEvNzBaWkdHLmpwZw.webp)

**Comment by ndneighbor** [comment]
Looking really good, going to kickstart the payout process for ya.

**Comment by melissa-hale** [comment]
Thanks for your patience @ItzDerock , and thank you for a solid template for imgproxy.

Just one action item -

I was able to get a dynamic key/pair generated with the `secret()` function by passing in: `${{ secret(32, "0123456789ABCDEF") }}`

Could you please update your template to use this and test my sanity by confirming it works for you as well?  If that checks out, please update your documentation accordingly.

Once I hear back, you'll get an email from me shortly after to arrange the payout!

**Comment by ItzDerock** [comment]
That works for me! I've updated the template accordingly.
