### ISSUE TITLE
Rust starter

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/templates#444]
### Contact Details

milo123459 on discord

### Template URL

https://railway.app/template/5HAMxu?referralCode=milo

### What does this template deploy?

This template deploys a Rust starter, as requested in #415

**Comment by melissa-hale** [comment]
Works like a charm @Milo123459. Please push the code and repoint the template to https://github.com/railwayapp-templates/rust-starter

Once you confirm done, I will start the payout!

**Comment by Milo123459** [comment]
i don't have perms on the repo

**Comment by melissa-hale** [comment]
You should be g2g now

**Comment by Milo123459** [comment]
done! it is now pointed at the railwayapp-templates repo.

**Comment by melissa-hale** [comment]
sweet, looks g!  could you send me an email and I'll start a thread? melissa@railway.app

**Comment by melissa-hale** [comment]
We might be able to bypass the email thing if you confirm you're happy to receive the payout through GH Sponsorship.  I see you're already setup for it!
