### ISSUE TITLE
Express Starter

### ISSUE THREAD

**Issue by vimode** [railwayapp/templates#445]
### Template URL

https://railway.app/template/Vp8hse

### What does this template deploy?

This fulfills the expectation of the issue #411 for an Express template.

**Comment by ndneighbor** [comment]
Just invited you to https://github.com/railwayapp-templates/node-express - this passed review. 

Next steps:

1) Upload the Template there
2) Update the repo link within the Template
3) Email me at angelo@railway.app when done.

Thanks again!

**Comment by vimode** [comment]
Done and done! Thank you.

**Comment by melissa-hale** [comment]
Hey @vimode , thanks for your patience!  Would you mind sending an email to me at melissa@railway.app so we can start the payout?  Thanks again :)
