### ISSUE TITLE
NocoDB Template

### ISSUE THREAD

**Issue by 6ixfalls** [railwayapp/templates#446]
### Contact Details

six@sixfalls.me

### Template URL

https://railway.app/template/opu-NU?referralCode=IQhE0B

### What does this template deploy?

This template deploys an instance of NocoDB, backed by PostgreSQL as well as Redis. Solves #432.

### Demo project

https://railway.app/project/232ec0f5-609d-49f1-afb4-003e6467d80e (deploys have been removed to cut costs)

**Comment by ndneighbor** [comment]
Working on payout, thanks!
