### ISSUE TITLE
RabbitMQ Template

### ISSUE THREAD

**Issue by 6ixfalls** [railwayapp/templates#447]
### Contact Details

six@sixfalls.me

### Template URL

https://railway.app/template/0ELOuE?referralCode=IQhE0B

### What does this template deploy?

This template deploys https://github.com/rabbitmq/rabbitmq-server with a config from https://github.com/6ixfalls/railway-rabbitmq, as well as additional "demo" services from the `quickstart` folder. The template includes:
- RabbitMQ Server (Management Plugin enabled on domain, AMQP on private networking)
- quickstart [send.js](https://github.com/6ixfalls/railway-rabbitmq/blob/main/quickstart/send.js)
- quickstart [receive.js](https://github.com/6ixfalls/railway-rabbitmq/blob/main/quickstart/receive.js)
Solves #425.

### Demo project

https://railway.app/project/922b218a-d18e-45c8-b33a-0e52bc7ee263 (deploys have been removed to cut costs)

**Comment by ndneighbor** [comment]
Resolved via Discord. Fantastic submission- thanks again!
