### ISSUE TITLE
Temporal Template

### ISSUE THREAD

**Issue by 6ixfalls** [railwayapp/templates#452]
### Contact Details

six@sixfalls.me

### Template URL

https://railway.app/template/AhDDtZ?referralCode=IQhE0B

### What does this template deploy?

This template deploys Temporal, an open source durable execution platform. This template includes the core Temporal server, the Temporal UI, a PostgreSQL database for Temporal data, as well as a hello-world template separated into a worker and a client. This solves #424.

### Demo project

https://railway.app/project/6b42a1d0-1c75-4b21-907f-c022f60f9973 (deploys may be removed to cut costs)

**Comment by ndneighbor** [comment]
Reviewing this now, thanks so much for this submission!

**Comment by ndneighbor** [comment]
Hey there @6ixfalls - so finally got around to deploying this in earnest.

It feels like there is some unclear instruction in setting up the `sql.yml` - although this may be familiar to Temporal users this might run into some issues where the Worker/Client might result in a crash-loop. Mind if you can resolve that or provide further instruction?

**Comment by ndneighbor** [comment]
Okay resolved via Discord- this is looking good. Push the code and repoint the Template over to https://github.com/railwayapp-templates/temporal and we can get this all closed out :)

**Comment by ndneighbor** [comment]
Working on payout, thanks!
