### ISSUE TITLE
[Template Submission]: Go Mux

### ISSUE THREAD

**Issue by brody192** [railwayapp/templates#454]
### Contact Details

https://discord.gg/railway

### Template URL

https://railway.app/template/_eGomU

### What does this template deploy?

A well-structured Go Mux starter template that showcases the usage of the Mux router. Include basic server setup, routing examples, and middleware implementation. As requested in [#414](https://github.com/railwayapp/templates/issues/414)

### Demo project

https://railway.app/project/97576470-281f-4bce-ad61-74a509f577b4

**Comment by ndneighbor** [comment]
Looking great, love the description!
