### ISSUE TITLE
[Template Submission]: Reverse Proxy

### ISSUE THREAD

**Issue by brody192** [railwayapp/templates#457]
### Contact Details

https://discord.gg/railway

### Template URL

https://railway.app/template/7uDSyj

### What does this template deploy?

Deploys a [Caddy](https://caddyserver.com/) service preconfigured to reverse proxy two internal services.

### Demo project

https://railway.app/project/35d8d571-4313-4049-9699-4e7db7f02a2f

**Comment by melissa-hale** [comment]
@brody192 you're getting a $50 payout on this one!

Here's your repo: https://github.com/railwayapp-templates/caddy-reverse-proxy

You know the drill, push code and update the config and lmk!

**Comment by brody192** [comment]
Done!

**Comment by melissa-hale** [comment]
completed
