### ISSUE TITLE
[Template Submission]: Chatwoot

### ISSUE THREAD

**Issue by brody192** [railwayapp/templates#458]
### Contact Details

https://discord.gg/railway

### Template URL

https://railway.app/template/ZBnDBU

### What does this template deploy?

This template deploys [chatwoot](https://www.chatwoot.com/)

### Demo project

https://railway.app/project/71daddc4-805b-4294-9a21-1e220ce479b6

**Comment by melissa-hale** [comment]
@brody192 you've got a payout coming for this one for $150 😄

**Comment by melissa-hale** [comment]
just push your code here: https://github.com/railwayapp-templates/chatwoot & update the template config.  once you ack, we're all set

**Comment by brody192** [comment]
Done!

**Comment by melissa-hale** [comment]
completed
