### ISSUE TITLE
Add Cube.dev (Core version) Template

### ISSUE THREAD

**Issue by apolo-damasco** [railwayapp/templates#465]
Cube.dev is a Semantic Layer that helps you connect, model, secure, cache and expose your data to every type of data consumer. They are really doing a great job and the product is evolving quickly.

Reasons to add:

- It requires several pieces of infrastructure that are hard to selfhost ([ref](https://cube.dev/blog/migrating-from-self-hosted-to-cube-cloud))
- It is a tool that every company needs since we are working with an increasing number of datasources. Data warehouses are established but the next step are semantic layers.

I believe they have an Apache 2.0 licence so there should not be any problem in that regard.

[Selhosting docs](https://cube.dev/docs/product/deployment/core)

![image](https://github.com/railwayapp/templates/assets/31798281/06204bc6-7c3e-419b-8998-79345aeebf53)

**Comment by brody192** [comment]
if you're offering the bounty for the template, that's cool, but railway is not currently running the template bounty program.

**Comment by apolo-damasco** [comment]
Understood. Edited.

**Comment by brody192** [comment]
I'm still not completely sure of the purpose for opening the issue? are you asking for someone to make this template for you?

**Comment by apolo-damasco** [comment]
Yes... Though by your response I am guessing that is not a possibility, and this is just a place to submit new templates?

**Comment by brody192** [comment]
this is neither a place to ask for templates nor to submit templates, you would instead want to ask the [community discord server](https://discord.gg/railway)
